<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GroundKit.Core\GroundKit.Core.csproj" />
    <ProjectReference Include="..\GroundKit.Storage.Sqlite\GroundKit.Storage.Sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
