<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GroundKit.Abstractions\GroundKit.Abstractions.csproj" />
    <ProjectReference Include="..\GroundKit.Core\GroundKit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" />
    <PackageReference Include="SQLitePCLRaw.bundle_winsqlite3" />
  </ItemGroup>

</Project>
