<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>groundkit</ToolCommandName>
    <PackageId>GroundKit</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GroundKit.Hosting\GroundKit.Hosting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>

</Project>
