<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <Using Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\groundkit-cli\GroundKit.Cli.csproj" />
    <ProjectReference Include="..\..\src\groundkit-mcp\GroundKit.Mcp.csproj" />
  </ItemGroup>

</Project>